name: OCaml

on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
#          - macos-latest
          - ubuntu-latest
          - windows-latest
        ocaml-version:
          - 4.12.0
          - 4.11.2
          - 4.10.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - run: opam install . --deps-only
      - run: opam exec -- dune build
      - run: opam install .

      - run: opam exec -- dune exec bravo silent check experiments/N3000.bravo
      - run: opam exec -- dune exec bravo silent check experiments/cat.bravo
      - run: opam exec -- dune exec bravo silent check experiments/circle.bravo
      - run: opam exec -- dune exec bravo silent check experiments/equiv.bravo
      - run: opam exec -- dune exec bravo silent check experiments/fiber.bravo
      - run: opam exec -- dune exec bravo silent check experiments/inf-group.bravo
      - run: opam exec -- dune exec bravo silent check experiments/path.bravo
      - run: opam exec -- dune exec bravo silent check experiments/test.bravo
      - run: opam exec -- dune exec bravo silent check experiments/univalence.bravo

